package com.siddhartha.walletwatcher.common.callback

enum class CallbackType {
    REDIRECTED_FROM_WELCOME_SCREEN, REDIRECTED_FROM_PHONE_SCREEN, REDIRECTED_FROM_OTP_SCREEN, REDIRECTED_FROM_NAME_SCREEN, REDIRECTED_FROM_FORM_SCREEN, RE_SEND_OTP, VERIFY_OTP
}